# build in configure for the pipeline
path:
  cutseq: ~/.micromamba/bin/cutseq
  samtools: ~/tools/samtools/samtools
  bamtools: ~/.local/bin/bamtools
  hisat3n: ~/tools/hisat2/hisat-3n
  hisat3nbuild: ~/tools/hisat2/hisat-3n-build
  hisat3ntable: ~/tools/hisat2/hisat-3n-table
  umicollapse: ~/tools/UMICollapse/umicollapse.jar

base_change: 'A,G'
splice_genome: true
libtype: STRANDED

# project specific parameters including data and reference

workdir: workspace

spike:
  - ../test/spike-in.fa
  - ../test/ERCC92.fa
  - ~/reference/genes/Arabidopsis_thaliana.rRNA.fa

genome:
  - ~/reference/genome/Arabidopsis_thaliana/TAIR10.fa

# TODO: if the genome index is not available, the pipeline will build it automatically
genome_index: ~/reference/genome/Arabidopsis_thaliana/hisat2_tx_3n/TAIR10.release57

samples:
  test1:
    data:
      - R1: ../test/test_R1.fq.gz
        R2: ../test/test_R2.fq.gz
