workdir: workspace

libtype: STRANDED

base_change: 'A,G'
markdup: true
strandness: true
gene_norc: true
splice_genome: true

# build in configure for the pipeline
path:
  cutseq: /opt/app_venv/bin/cutseq
  samtools: /pipeline/samtools/samtools
  umicollapse: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/UMICollapse/umicollapse.jar bam
  markduplicates: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/gatk/gatk.jar MarkDuplicates
  hisat3n: /pipeline/hisat2-hisat-3n/hisat-3n
  hisat3nbuild: /pipeline/hisat2-hisat-3n/hisat-3n-build
  hisat3ntable: /pipeline/hisat2-hisat-3n/hisat-3n-table
  joinPileup: /pipeline/bin/join_pileup.py
  filterSites: /pipeline/bin/filter_sites.py
