workdir: workspace

libtype: STRANDED

base_change: 'A,G'
markdup: true
strandness: true
gene_norc: true
splice_genome: true

# build in configure for the pipeline
path:
  cutseq: /usr/local/bin/cutseq
  samtools: /pipeline/samtools/samtools
  hisat3n: /pipeline/hisat2-hisat-3n/hisat-3n
  hisat3nbuild: /pipeline/hisat2-hisat-3n/hisat-3n-build
  hisat3ntable: /pipeline/hisat2-hisat-3n/hisat-3n-table
  joinPileup: /pipeline/bin/join_pileup.py
  filterSites: /pipeline/bin/filter_sites.py
