# build in configure for the pipeline
path:
  cutseq: /opt/app_venv/bin/cutseq
  samtools: /pipeline/samtools/samtools
  umicollapse: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/UMICollapse/umicollapse.jar bam
  markduplicates: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/gatk/gatk.jar MarkDuplicates
  hisat3n: /pipeline/hisat2-hisat-3n/hisat-3n
  hisat3nbuild: /pipeline/hisat2-hisat-3n/hisat-3n-build
  pb: /pipeline/bin/pb
  collectReadCounts: python ./bin/collect_read_counts.py
  convertPileup: python ./bin/pileup_to_arrow.py
  joinPileup: /pipeline/bin/join_pileup.py
  filterSites: /pipeline/bin/filter_sites.py

# m6A method, use A to G mutation
base_change: 'A,G'

# can be "ECLIP10", "ECLIP6", "TAKARAV3", "SACSEQV3", "STRANDED"
libtype: ECLIP6
# with umi in the library or not
with_umi: true
# by default, the pipeline will force remove the PCR duplicates based on the UMI
# if UMI is not available, you can toggle the markdup to `false` to skip the PCR duplicate removal
markdup: true
# by default, the pipeline will use the strandness information from the library
# if the strandness is not available, set the strandness to `false`
strandness: true

## run the analysis
workdir: workspace

gene_norc: true
splice_genome: true

cutoff:
  min_uncon: 1
  min_depth: 10
  min_ratio: 0.05
  min_pval: 0.05
