#!/usr/bin/env bash
#
# Copyright © 2024 Ye Chang yech1990@gmail.com
# Distributed under terms of the GNU license.
#
# Created: 2024-11-07 18:49

logo="
\033[1;32m ███╗   ███╗ ██████╗  █████╗ \033[0m       ██████╗ █████╗ ███╗   ███╗\033[0m
\033[1;32m ████╗ ████║██╔════╝ ██╔══██╗\033[0m      ██╔════╝██╔══██╗████╗ ████║\033[0m
\033[1;32m ██╔████╔██║███████╗ ███████║\033[0m█████╗██║     ███████║██╔████╔██║\033[0m
\033[1;32m ██║╚██╔╝██║██╔═══██╗██╔══██║\033[0m╚════╝██║     ██╔══██║██║╚██╔╝██║\033[0m
\033[1;32m ██║ ╚═╝ ██║╚██████╔╝██║  ██║\033[0m      ╚██████╗██║  ██║██║ ╚═╝ ██║\033[0m
\033[1;32m ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝\033[0m       ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝\033[0m
"

printf "$logo\n"

# Set default values
snake="/pipeline/Snakefile"
conf="data.yaml"

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
  -j | --jobs | --cores)
    cores_cmd="$2"
    shift
    shift
    ;;
  -c | --conf)
    conf="$2"
    shift
    shift
    ;;
  --mysnake)
    snake="$2"
    shift
    shift
    ;;
  *)
    POSITIONAL_ARGS+=("$1")
    shift
    ;;
  esac
done
set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ ! -f "${conf}" ]; then
  echo "${conf} can not be found!"
  exit 1
else
  python /pipeline/validator "${conf}"
fi
if [ -z "${cores_cmd}" ]; then
  cores_conf=$(python -c 'import yaml, sys;print(yaml.safe_load(open(sys.argv[1],"r")).get("cores",""))' "${conf}")
  if [ -z "${cores_conf}" ]; then
    cores=64
  else
    cores=${cores_conf}
  fi
else
  cores=${cores_cmd}
fi

export LC_ALL=C.UTF-8
LOGFILE="CAMSEQ_LOG_$(date +"%F-%H%M%S").txt"
echo -e "\033[0;32mREAD DEBUG LOG AT\033[0m ${LOGFILE}"
printf "\033[0;33m Analyzing...\033[0m"
snakemake --rerun-incomplete --quiet rules --jobs "${cores}" --snakefile "${snake}" --configfiles /pipeline/default.yaml "${conf}" "$@" 1>"${LOGFILE}" 2>"${LOGFILE}"
if [ $? -eq 0 ]; then
  printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
  printf "\033[0;32m\xE2\x9C\x94\033[0m Successfully finished all jobs.\n"
else
  printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
  printf "\033[0;31m\xE2\x9D\x8C\033[0m Jobs exit with error!\n"
fi
