name: Create Release Package

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v1.0, v2.0.1

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone (depth 1) for main repo and submodules
          submodules: 'recursive' # Initialize and update submodules recursively

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Clean submodule large/dev/CI files (keep .git and git config files for now)
        run: |
          echo "Cleaning submodule large/development content (docs, tests, examples, CI configs, etc.)..."
          git submodule foreach --recursive '
            echo "Processing submodule: $name at $path (large/dev content cleaning)"
            rm -rf docs test tests example examples examples-data test-data .github .travis.yml .circleci.yml appveyor.yml Jenkinsfile
            true
          '
          echo "Submodule large/dev content cleaning complete."

      - name: Create package directory
        run: mkdir release_package

      - name: Copy specified project folder to package
        run: |
          echo "Copying specified project folder(s)..."
          if [ -d "external" ]; then
            echo "Copying external/..."
            cp -r external release_package/
          else
            echo "external/ folder not found, skipping."
          fi

      - name: Copy specified root files to package
        run: |
          echo "Copying specified root files..."
          if [ -f "Dockerfile" ]; then cp Dockerfile release_package/; else echo "Dockerfile not found, skipping."; fi
          if [ -f "LICENSE" ]; then cp LICENSE release_package/; else echo "LICENSE not found, skipping."; fi
          if [ -f "Snakefile" ]; then cp Snakefile release_package/; else echo "Snakefile not found, skipping."; fi
          if [ -f "VERSION" ]; then cp VERSION release_package/; else echo "VERSION not found, skipping."; fi
          if [ -f "default.yaml" ]; then cp default.yaml release_package/; else echo "default.yaml not found, skipping."; fi

      - name: Finalize package content (remove .git, .gitmodules, etc.)
        # This step runs *after* all desired files are copied into release_package
        # and *before* creating the archive.
        run: |
          echo "Finalizing package content in release_package..."
          if [ ! -d "release_package" ]; then
            echo "Error: release_package directory does not exist. Check previous copy steps."
            exit 1
          fi

          echo "Removing .git folders/files from release_package..."
          find release_package -type d -name ".git" -print -exec rm -rf {} +
          find release_package -type f -name ".git" -print -exec rm -f {} + # Handles submodule .git files if they are text files pointing to gitdir

          echo "Removing .gitmodules files from release_package..."
          find release_package -type f -name ".gitmodules" -print -exec rm -f {} +

          echo "Removing .gitattributes files from release_package..."
          find release_package -type f -name ".gitattributes" -print -exec rm -f {} +

          echo "Removing .gitignore files from release_package..."
          find release_package -type f -name ".gitignore" -print -exec rm -f {} +

          echo "Listing contents of release_package after final cleaning:"
          ls -R release_package
          echo "--- End of package content listing ---"

      - name: Create archive
        run: |
          cd release_package
          tar -czvf ../${{ github.event.repository.name }}-${{ env.TAG_NAME }}.tar.gz .
          # Or for a zip file:
          # zip -r ../${{ github.event.repository.name }}-${{ env.TAG_NAME }}.zip .
          cd ..
        id: archive_details

      - name: Upload Release Asset (Workflow Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ env.TAG_NAME }}_package
          path: ${{ github.event.repository.name }}-${{ env.TAG_NAME }}.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ env.TAG_NAME }}.tar.gz # Updated naming
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }} # e.g., Release v1.0
          body: 'Release notes for ${{ github.ref_name }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
